function plotSensGraphs(paramVals, simMode, fixedVals, dataVals, ...
    simTimes, savePlot, fileBase)

% Create a series of plots of simulations for sensitivity analysis on the parameters.
% 
% The y-axis should be a log scale. There will be one graph for each 
% initial value and three traces on each graph
%
% 1. Baseline - solid lines
% 2. Down values - dashed lines
% 3. Up values - dotted lines
%
% function plotSensGraphs(paramVals, simMode, fixedVals, dataVals, ...
%    simTimes, savePlot, fileBase)
%
% paramVals     - The parameters for the simulation
% simMode       - Which ODE equations should be used
% fixedVals     - Some values which are not changed
% dataVals		- Initial species numbers
% simTimes      - Time points for which data should be plotted.
% savePlot      - Should plots be saved?
% fileBase      - Base filename for all plots from this simulation

% Version    Author       Date      Affiliation
% 1.00       J K Summers  05/12/19  Kreft Lab - School of Biosciences -
%                                   University of Birmingham

baseVals = getSpecies(paramVals, fixedVals, dataVals, simTimes, ...
    simMode, false);

for iParm = 1:size(dataVals, 1)
    sensVals = dataVals;
    sensVals(iParm) = 10^(log10(dataVals(iParm)) + 1);
    upVals(iParm, :, :, :) = getSpecies(paramVals, fixedVals, sensVals, ...
        simTimes, simMode, false);

    sensVals(iParm) = 10^(log10(dataVals(iParm)) - 1);
    downVals(iParm, :, :, :) = getSpecies(paramVals, fixedVals, ...
        sensVals, simTimes, simMode, false);
end

fileName = [fileBase ' E coli only species values'];

plotSensFig(simTimes, baseVals(:, 1, 1:2), upVals(1, :, 1, 1:2), ...
    downVals(1, :, 1, 1:2), 'mb', ...
    {'Species sensitivities', 'for E. coli only', ''}, savePlot, fileName);

fileName = [fileBase ...
    ' E coli and Bdellovibrio species values, vary E. coli'];
plotSensFig(simTimes, baseVals(:, 2, 1:3), upVals(2, :, 2, 1:3), ...
    downVals(2, :, 2, 1:3), 'mbr', ...
    {'Species sensitivities', ...
    'for E. coli and Bdellovibrio to E. coli', ''}, ...
    savePlot, fileName);

fileName = [fileBase ' E coli and Halophage species values vary E. coli'];
plotSensFig(simTimes, baseVals(:, 3, [1 2 4]), ...
    upVals(3, :, 3, [1 2 4]), downVals(3, :, 3, [1 2 4]), 'mbg', ...
    {'Species sensitivities', ...
    'for E. coli and Halophage to E. coli', ''}, ...
    savePlot, fileName);

fileName = ...
    [fileBase ...
    ' E coli, Bdellovibrio and Halophage species values vary E. coli'];
plotSensFig(simTimes, baseVals(:, 4, 1:4), upVals(4, :, 4, 1:4), ...
    downVals(4, :, 4, 1:4), 'mbrg', ...
    {'Species sensitivities', ...
    'for E. coli, Bdellovibrio and Halophage to E. coli', ''}, ...
    savePlot, fileName);

fileName = ...
    [fileBase ...
    ' E coli and Bdellovibrio species values vary Bdellovibrio'];
plotSensFig(simTimes, baseVals(:, 2, 1:3), upVals(5, :, 2, 1:3), ...
    downVals(5, :, 2, 1:3), 'mbr', ...
    {'Species sensitivities', ...
    'for E. coli and Bdellovibrio to Bdellovibrio', ''}, savePlot, ...
    fileName);

fileName = ...
    [fileBase ...
    ' E coli, Bdellovibrio and Halophage species values vary Bdellovibrio'];
plotSensFig(simTimes, baseVals(:, 4, 1:4), upVals(6, :, 4, 1:4), ...
    downVals(6, :, 4, 1:4), 'mbrg', ...
    {'Species sensitivities', ...
    'for E. coli, Bdellovibrio and Halophage to Bdellovibrio', ''}, ...
    savePlot, fileName);

fileName = ...
    [fileBase ...
    ' E coli and Halophage species values vary Halophage'];
plotSensFig(simTimes, baseVals(:, 3, [1 2 4]), ...
    upVals(7, :, 3, [1 2 4]), downVals(7, :, 3, [1 2 4]), 'mbg', ...
    {'Species sensitivities', ...
    'for E. coli and Halophage to Halophage', ''}, ...
    savePlot, fileName);

fileName = ...
    [fileBase ...
    ' E coli, Bdellovibrio and Halophage species values vary Halophage'];
plotSensFig(simTimes, baseVals(:, 4, 1:4), upVals(8, :, 4, 1:4), ...
    downVals(8, :, 4, 1:4), 'mbrg', ...
    {'Species sensitivities', ...
    'for E. coli, Bdellovibrio and Halophage to Halophage', ''}, ...
    savePlot, fileName);

end